name: NOTE_DEPLOY

on:
  push:
    branches:
      - master

env:
  GIT_USER: fzf404
  GIT_EMAIL: nmdfzf404@163.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Setup
        run: |
          npm install

      - name: Theme
        run: |
          git clone https://github.com/fzf404/rdoc-theme-fzf.git
          rm -rf node_modules/rdoc/theme/default/*
          mv rdoc-theme-fzf/* node_modules/rdoc/theme/default/

      - name: Build
        run: |
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .rdoc-dist
